/// Code Extension
///
/// Generated by elfiee-ext-gen - Modify as needed
use serde::{Deserialize, Serialize};
use specta::Type;

// ============================================================================
// Module Exports
// ============================================================================

pub mod code_read;
pub use code_read::*;

pub mod code_write;
pub use code_write::*;

// ============================================================================
// Payload Definitions
// ============================================================================

/// Payload for CodeRead
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct CodeReadPayload {}

/// Payload for CodeWrite
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct CodeWritePayload {
    /// The source code text content to write
    pub content: String,
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests;
