/// Terminal Extension
///
/// Generated by elfiee-ext-gen - Modify as needed

use serde::{Deserialize, Serialize};
use specta::Type;

// ============================================================================
// Module Exports
// ============================================================================


pub mod terminal_read;
pub use terminal_read::*;

pub mod terminal_write;
pub use terminal_write::*;

pub mod terminal_execute;
pub use terminal_execute::*;


// ============================================================================
// Payload Definitions
// ============================================================================


/// Payload for TerminalRead
///
/// Used for querying terminal state and history. Currently no parameters needed
/// as it returns the entire terminal state.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct TerminalReadPayload {
    // No fields needed for basic read operation
    // In the future, could add filters like:
    // pub last_n_entries: Option<usize>,
    // pub since_timestamp: Option<String>,
}

/// Payload for TerminalExecute
///
/// Executes a command in the terminal and stores the result in history.
///
/// Fields:
/// - command: The command string to execute
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct TerminalExecutePayload {
    /// The command to execute
    pub command: String,
}

/// Payload for TerminalWrite
///
/// Used for writing content directly to the terminal without executing commands,
/// or for saving the entire terminal buffer content to the block.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct TerminalWritePayload {
    /// Content to write to the terminal. Can be text or any JSON value.
    pub data: Option<serde_json::Value>,
    
    /// Saved terminal content (for save functionality)
    pub saved_content: Option<String>,
    
    /// Timestamp when content was saved
    pub saved_at: Option<String>,
    
    /// Current directory when content was saved
    pub current_directory: Option<String>,
    
    /// Root path for the terminal session
    pub root_path: Option<String>,
    
    /// Current absolute path
    pub current_path: Option<String>,
    
    /// Latest Markdown snapshot block ID (for Save to Markdown functionality)
    pub latest_snapshot_block_id: Option<String>,
}



// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests;

#[cfg(test)]
mod terminal_save_test;
