/// Capability: read
///
/// Generated by elfiee-ext-gen - Implement the logic below

use crate::capabilities::core::CapResult;
use crate::models::{Block, Command, Event};
use capability_macros::capability;

/// Handler for terminal.read capability.
///
/// Reads the terminal history and current state. This is a read-only operation
/// that doesn't modify the block, so it returns an empty event vector.
///
/// # Arguments
/// * `cmd` - The command containing the payload
/// * `block` - Optional block to operate on
///
/// # Returns
/// * `Ok(Vec<Event>)` - Empty vector (read-only operation)
/// * `Err(String)` - Error description
///
#[capability(id = "terminal.read", target = "terminal")]
fn handle_read(_cmd: &Command, block: Option<&Block>) -> CapResult<Vec<Event>> {
    let _block = block.ok_or("Block required for terminal.read")?;
    
    // Terminal read is a query operation that doesn't modify state
    // The frontend can access block.contents directly for display
    // No events are generated for read operations
    Ok(vec![])
}
