/// Todo Extension
///
/// Generated by elfiee-ext-gen - Modify as needed

use serde::{Deserialize, Serialize};
use specta::Type;

// ============================================================================
// Payload Definitions
// ============================================================================


/// Payload for TodoAddItem
///
/// TODO: Define the specific fields needed for this capability.
///
/// Suggested fields (modify as needed):

/// - text: String - The text content to add

/// - priority: Option<u32> - Optional priority level

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct TodoAddItemPayload {
    // TODO: Replace this generic field with specific fields
    pub data: serde_json::Value,
}


/// Payload for TodoToggleItem
///
/// TODO: Define the specific fields needed for this capability.
///
/// Suggested fields (modify as needed):

/// - item_id: String - ID of the item to toggle

/// - status: bool - New status

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct TodoToggleItemPayload {
    // TODO: Replace this generic field with specific fields
    pub data: serde_json::Value,
}


