/// Capability: list
///
/// Generated by elfiee-ext-gen - Implement the logic below

use super::DirectoryListPayload;
use crate::capabilities::core::{create_event, CapResult};
use crate::models::{Block, Command, Event};
use capability_macros::capability;
use std::fs;
use std::path::Path;

/// Handler for list capability.
///
/// TODO: Implement the capability logic here.
///
/// # Arguments
/// * `cmd` - The command containing the payload
/// * `block` - Optional block to operate on
///
/// # Returns
/// * `Ok(Vec<Event>)` - Events to be committed
/// * `Err(String)` - Error description
///
#[capability(id = "directory.list", target = "directory")]
fn handle_list(cmd: &Command, block: Option<&Block>) -> CapResult<Vec<Event>> {
// Step 1: 反序列化 payload
      let payload: DirectoryListPayload = serde_json::from_value(cmd.payload.clone())
          .map_err(|err| format!("Invalid payload for directory.list: {}", err))?;

      // Step 2: 校验输入
      if payload.root.trim().is_empty() {
          return Err("DirectoryListPayload.root must not be empty".into());
      }

      let block = block.ok_or("Block required for directory.list capability")?;
      let path = Path::new(&payload.root);
      if !path.exists() {
          return Err(format!("Path '{}' does not exist", payload.root));
      }
      if !path.is_dir() {
          return Err(format!("Path '{}' is not a directory", payload.root));
      }

      // Step 3: 执行业务逻辑（这里只做单层列举）
      let mut entries = Vec::new();
      for entry in fs::read_dir(path).map_err(|err| format!("Failed to read directory: {}", err))? {
          let entry = entry.map_err(|err| format!("Failed to read entry: {}", err))?;
          let file_type = entry.file_type().map_err(|err| format!("Failed to determine entry type: {}", err))?;
          let name = entry.file_name().to_string_lossy().to_string();

          if !payload.include_hidden && name.starts_with('.') {
              continue;
          }

          entries.push(serde_json::json!({
              "name": name,
              "is_dir": file_type.is_dir(),
              "is_file": file_type.is_file(),
          }));
      }

      // TODO: 后续可以参考 payload.recursive / payload.max_depth 做递归遍历
      let value = serde_json::json!({
          "root": payload.root,
          "recursive": payload.recursive,
          "include_hidden": payload.include_hidden,
          "max_depth": payload.max_depth,
          "entries": entries,
      });

      // Step 4: 创建事件
      let event = create_event(
          block.block_id.clone(),          // entity
          "directory.list",                // cap_id
          value,
          &cmd.editor_id,
          1,                               // 占位的向量时钟，Actor 会写真实值
      );

      Ok(vec![event])
}
