/// Directory Extension
///
/// Generated by elfiee-ext-gen - Modify as needed
use serde::{Deserialize, Serialize};
use specta::Type;

// ============================================================================
// Module Exports
// ============================================================================

pub mod directory_import;
pub use directory_import::*;

pub mod directory_export;
pub use directory_export::*;

pub mod directory_write;
pub use directory_write::*;

pub mod directory_create;
pub use directory_create::*;

pub mod directory_delete;
pub use directory_delete::*;

pub mod directory_rename;
pub use directory_rename::*;

pub mod directory_rename_with_type_change;
pub use directory_rename_with_type_change::*;

pub mod elf_meta;

// ============================================================================
// Payload Definitions
// ============================================================================

/// Payload for DirectoryImport
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct DirectoryImportPayload {
    pub source_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_path: Option<String>,
}

/// Payload for DirectoryExport
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct DirectoryExportPayload {
    pub target_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_path: Option<String>,
}

pub use directory_write::DirectoryWritePayload;

/// Payload for DirectoryCreate
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct DirectoryCreatePayload {
    pub path: String,
    #[serde(rename = "type")]
    pub entry_type: String,
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub block_type: Option<String>,
}

/// Payload for DirectoryDelete
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct DirectoryDeletePayload {
    pub path: String,
}

/// Payload for DirectoryRename
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct DirectoryRenamePayload {
    pub old_path: String,
    pub new_path: String,
}

/// Payload for DirectoryRenameWithTypeChange
///
/// Atomically renames a file entry and changes its block type in a single transaction.
/// This ensures consistency when file extension changes require block type updates.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct DirectoryRenameWithTypeChangePayload {
    pub old_path: String,
    pub new_path: String,
    /// Optional: Directly specify the new block type (e.g., "markdown", "code")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub block_type: Option<String>,
    /// Optional: Infer block type from file extension (e.g., "md", "rs", "txt")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_extension: Option<String>,
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests;
